sarafun:
  bt_action_nodes:
    align:
      action_server_name: /sarafun/bt_nodes_test/align
      bt_client_name: align_action
      timeout: 60
    assembled:
      action_server_name: /sarafun/bt_nodes_test/assembled
      bt_client_name: assembled_action
      timeout: 60
    contact:
      action_server_name: /sarafun/bt_nodes_test/contact
      bt_client_name: contact_action
      timeout: 60
    grasp:
      action_server_name: /sarafun/bt_nodes_test/grasp
      bt_client_name: grasp_action
      timeout: 60
    initial:
      action_server_name: /sarafun/bt_nodes_test/initial
      bt_client_name: initial_action
      timeout: 60
    move:
      action_server_name: /sarafun/bt_nodes_test/move
      bt_client_name: move_action
      timeout: 60
    pickup:
      action_server_name: /sarafun/bt_nodes_test/pickup
      bt_client_name: pickup_action
      timeout: 60
    retract:
      action_server_name: /sarafun/bt_nodes_test/retract
      bt_client_name: retract_action
      timeout: 60
